### PR TITLE
my index website

### PR DESCRIPTION
**Pull request by Madhavman**
i am again making a pull request because of network issue , you can change accordingly touch on the button near book reader .i am a begginer if there is a mistake don't mark spam rather than tell me

### CODE REVIEW

**Comment by simranquirky** [comment]
if you continue to generate pull request uselessly , be sure I will mark it as spam.

**Comment by Madhavman** [comment]
please merge

**Comment by Madhavman** [comment]
so what i do i have done my work

**Comment by Madhavman** [comment]
i have generate first time because of network and again this is only 2 time .i have done my work

**Comment by simranquirky** [comment]
look I checked your profile and let me give you a piece of advice **stop generating worthless PRs.**

### First try to understand the repo, look at the issues and then generate some useful PRs

**Comment by Madhavman** [comment]
ok

**Comment by Madhavman** [comment]
Very sorry please don't Mark can I design an about page for you if you like

**Comment by Madhavman** [comment]
how dar you to mark spam i am helping

**Pull request closed without merging**
